### ISSUE TITLE
TCP/IP 协议: 卷1

### ISSUE THREAD

**Issue by 0XFF-96** [Alex1996a/golang-snippet#8]
### 学习资源地址
1、http://www.52im.net/topic-tcpipvol1.html
2、TCP/IP 学习笔记， https://www.cnblogs.com/fengzanfeng/articles/1339347.html 

### 必读 RPC
1- https://tools.ietf.org/html/rfc1219 

### 参考资料

- 什么是【广播域】 和 【冲突域 】 https://www.zhihu.com/question/27723724

**Comment by 0XFF-96** [comment]
### select、epoll 和 IO  多路复用的区别

![Uploading image.png…]()

- [ ]: https://www.youtube.com/watch?v=4gv9reEaD7g 【非常好的讲解】 


- [ ]: https://github.com/H00ly666/web-server

**Comment by 0XFF-96** [comment]
### golang tcp epoll 的相关代码实现

1、https://studygolang.com/articles/22460
2、百万连接 epoll 的相关文章， https://colobu.com/2017/11/29/event-loop-networking-in-Go/  
3、example epoll: https://gist.github.com/tevino/3a4f4ec4ea9d0ca66d4f 
4、https://github.com/H00ly666/web-server

**Comment by 0XFF-96** [comment]
### 培训课程
1、PDF来自2014年Linux系统编程 邢文鹏的课， https://www.youtube.com/watch?v=OV2xASYE5yg

**Comment by 0XFF-96** [comment]
### TODO
- [x] 2章·链路层··········································································································读书笔记习题答案·- [ ] 15页
- [x] 3章·IP：网际协议································································································读书笔记习题答案·- [ ] 24页
- [x] 4章·ARP：地址解析协议·····················································································读书笔记习题答案·- [ ] 38页
- [x] 5章·RARP：逆地址解析协议···············································································读书笔记习题答案·- [ ] 47页
- [x] 6章·ICMP：Internet控制报文协议········································································读书笔记习题答案·- [ ] 50页
- [x] 7章·Ping程序·······································································································读书笔记习题答案·- [ ] 61页
- [x] 8章·Traceroute程序·····························································································读书笔记习题答案·- [ ] 71页
- [x] 9章·IP选路···········································································································读书笔记习题答案·- [ ] 83页
- [x] 10章·动态选路协议································································································读书笔记习题答案·- [ ] 95页
- [x] 11章·UDP：用户数据报协议··················································································读书笔记习题答案·- [ ] 107页
- [x] 12章·广播和多播···································································································读书笔记习题答案·- [ ] 128页
- [ ] 13章·IGMP：Internet组管理协议···········································································读书笔记习题答案·- [ ] 136页
- [ ] 14章·DNS：域名系统····························································································读书笔记习题答案·- [ ] 142页
- [ ] 15章·TFTP：简单文件传送协议············································································读书笔记习题答案·- [ ] 159页
- [ ] 16章·BOOTP: 引导程序协议·················································································读书笔记习题答案·- [ ] 163页
- [ ] 17章·TCP：传输控制协议·····················································································读书笔记习题答案·- [ ] 170页
- [ ] 18章·TCP连接的建立与终止·················································································读书笔记习题答案·- [ ] 174页
- [ ] 19章·TCP的交互数据流························································································读书笔记习题答案·- [ ] 200页
- [ ] 20章·TCP的成块数据流························································································读书笔记习题答案·- [ ] 209页
- [ ] 21章·TCP的超时与重传························································································ 习题答案·- [ ] 226页
- [ ] 22章·TCP的坚持定时器························································································ 习题答案·- [ ] 245页
- [ ] 23章·TCP的保活定时器························································································ 习题答案·- [ ] 251页
- [ ] 24章·TCP的未来和性能························································································ 习题答案·- [ ] 256页
- [ ] 25章·SNMP：简单网络管理协议··········································································· 习题答案·- [ ] 270页
- [ ] 26章·Telnet和Rlogin：远程登录··········································································· 习题答案·- [ ] 293页
- [ ] 27章·FTP：文件传送协议····················································································· 习题答案·- [ ] 316页
- [ ] 28章·SMTP：简单邮件传送协议··········································································· 习题答案·- [ ] 332页
- [ ] 29章·网络文件系统······························································································· 习题答案·- [ ] 347页
- [ ] 30章·其他的TCP/IP应用程序················································································· 习题答案·- [ ] 363页

**Comment by 0XFF-96** [comment]
### 请计算最多有多少个A类、B类、C类网络号（tcp/ip协议详解-习题1.1） 
- https://blog.csdn.net/zhengwish/article/details/80053596 


### RFC 从何而来？

> Request For Comments (RFC)，是一系列以bai编号排定的文件。文件收du集了有关因特网zhi相关资讯，以及UNIX和因特网社dao群的软件文件。目前RFC文件是由Internet Society（ISOC）所赞助发行。
RFC 1000就是编号为1000的一个文件！

**Comment by 0XFF-96** [comment]
### 链路层

### 链路层的主要功能
- ？


### 链路层的三个目的

- 1）为IP模块发送和接收IP数据报；
- 2）为ARP模块发送ARP请求和接收ARP应答
- 3）为RARP发送RARP请求和接收RARP应答

### 以太网帧格式
- 两种帧格式都采用48 bit（6字节）的目的地址和源地址（

### SLIP 的缺点
> 它是一种在串行线路上对IP数据报进行封装
- 每一端必须知道对方的IP地址
- 数据帧中没有类型字段
- SLIP 没有校验和

### PPP 对比的优点
- PPP支持在单根串行线路上运行多种协议，不只是IP协议；
- 每一帧都有循环冗余检验；
- 通信双方可以进行IP地址的动态协商(使用IP网络控制协议)；
- 与CSLIP类似，对TCP和IP报文首部进行压缩；
- 链路控制协议可以对多个数据链路选项进行设置。

### MTU
- traceroute程序也是用这个方法来确定到达目的节点的路径MTU 
- 如果IP层有一个数据报要传，而且数据的长度比链路层的MTU还大,那么IP层就需要进行分片（fragmentation


### 了解 netstat 的相关使用
- https://www.cnblogs.com/ggjucheng/archive/2012/01/08/2316661.HTML 

### 能不能思考一下，如何用 Golang 语言实现链路层？

![image](https://user-images.githubusercontent.com/19239600/86901226-e4dc5700-c13e-11ea-8da0-933d67e74045.png)


### Linux中本机和本机Socket通信会走网卡吗？

- https://www.zhihu.com/question/43590414
- 相关问题， https://www.cnblogs.com/hustcat/p/3920940.html

**Comment by 0XFF-96** [comment]
### IP 

有两个主要的特点： 

- 不可靠，Unreliable。 不能保证 IP 数据报能成功到达目的地
- 无连接 ( connectionless ), IP 数据报不维护后续状态信息

设备与 IP 地址的关系
- 同一个网络设备，可以有多个 IP 地址。
- 一个 IP 地址只能对应一个网络设备。

### 协议

![image](https://user-images.githubusercontent.com/19239600/87014274-7b238200-c1fe-11ea-9bd0-39492c005285.png)


- 总长度字段， 该字段长16比特，所以IP数据报最长可达65535字节
> 总长度字段是IP首部中必要的内容，因为一些数据链路（如以太网）需要填充一些数据以达到最小长度

- 标识字段，标识字段唯一地标识主机发送的每一份数据报。通常每发送一份报文它的值就会加1。在11.5节介绍分片和重组时再详细讨论它
- TTL（time-to-live）生存时间字段设置了数据报可以经过的最多路由器数
- Identification （标识符)。 用来实现IP分片的重组，标识分片属于哪个进程，不同进程通过不同ID区分

### IP 路由选择 

> 。如果目的主机与源主机直接相连（如点对点链路）或都在一个共享网络上（以太网或令牌环网），那么IP数据报就直接送到目的主机上。否则，主机把数据报发往一默认的路由器上


### 路由表

- 目的地址,  主机地址 or 网络地址
- 下一站， next-hop router 
- 标识，指明目的 IP 地址，是网络地址还是主机地址
- 为数据报指定网络接口。 

### 路由搜索过程
> 为一个网络指定路由器，而不需要为一个主机指定路由器

- ？ 处理的话，会检查 TTL 生命周期，则将 IP 数据包抛弃。 


-找到与目的 IP 地址完全匹配的 entry ( 网络号与主机号） 都匹配
- 找到与目的网络号匹配的 entry 
- 找到  default 的目录



### 为什么 IP 地址需要分类？
> 如果不分类会发生什么？

- https://www.zhihu.com/question/31766172
- 减少 路由表的记录📝 

https://network.51cto.com/art/201911/605681.htm


### 利用抓包实战 IP 协议
- https://zhuanlan.zhihu.com/p/29287795 

### 为什么需要 TTL ？

- TTL生存时间字段可以实现通信防环

**Comment by 0XFF-96** [comment]
### ARP 
> ARP为IP地址到对应的硬件地址之间提供动态映射

- ARP高效运行的关键是由于每个主机上都有一个ARP高速缓存。这个高速缓存存放了最近Internet地址到硬件地址之间的映射记录

使用 `arp -a ` 查询

### 以太网，最小帧长度

> 由于ARP请求或回答的数据帧长都是42字节（28字节的ARP数据，14字节的以太网帧头），因此，每一帧都必须加入填充字符以达到以太网的最小长度要求：60字节


### ARP 代理
- 不在同一个【以太网】，如果需要应答对方的 ARP 请求，就需要 ARP 代理。 

- 作用, 1、相互隐藏物理网络。 2、两个物理网络，可以使用相同的网络号 

> 只要把中间的路由器设置成一个ARP代理，以响应一个网络到另一个网络主机的ARP请求。这种技术在过去用来隐藏一组在不同物理电缆上运行旧版TCP/IP的主机

### RARP 
-  作为用户进程的RARP服务器
-  每个网络有多个RARP服务器 
> RARP在概念上很简单，但是一个RARP服务器的设计与系统相关而且比较复杂。相反，提供一个ARP服务器很简单，通常是TCP/IP在内核中实现的一部分。由于内核知道IP地址和硬件地址，因此当它收到一个询问IP地址的ARP请求时，只需用相应的硬件地址来提供应答就可以了

**Comment by 0XFF-96** [comment]
### IMCP 

- ICMP报文是在IP数据报内部被传输的。 IP 首部（20 bytes) + ICMP 报文


###  ICMP报文的类型

- ICMP时间戳请求允许系统向另一个系统查询当前的时间。返回的建议值是自午夜开始计算的毫秒数
-  ICMP地址掩码请求与应答
- ICMP端口不可达差错

**Comment by 0XFF-96** [comment]
### Ping 

- 一般来说，如果不能 ping 到某台主机，就不能 Telnet 或者 FTP 到那台主机
> 一台主机的可达性可能不只取决于IP层是否可达，还取决于使用何种协议以及端口号。Ping程序的运行结果可能显示某台主机不可达，但我们可以用Te lnet远程登录到该台主机的25号端口（邮件服务器）

**Comment by 0XFF-96** [comment]
### Traceroute 程序

> Traceroute程序是一个能更深入探索TCP/IP协议的方便可用的工具。尽管不能保证从源端发往目的端的两份连续的IP数据报具有相同的路由，但是大多数情况下是这样的。

- Traceroute程序只需要目的端运行一个UDP模块 

- TTL字段的目的是防止数据报在选路时无休止地在网络中流动。


### Traceroute 程序的操作过程
- 它发送一份TTL字段为1的IP数据报给目的主机。处理这份数据报的第一个路由器将TTL值减1，丢弃该数据报，并发回一份超时ICMP报文

- 然后Traceroute程序发送一份TTL值为2的数据报，这样我们就可以得到第二个路由器的地址

- 如何判断是否已经到达目的主机了呢？
> 发送一份UDP数据报给目的主机，但它选择一个不可能的值作为UDP端口号（大于30 000），使目的主机的任何一个应用程序都不可能使用该端口


### traceroute 的工作原理

> 在一个TCP/IP网络中，traceroute程序是不可缺少的工具。其操作很简单：开始时发送一个TTL字段为1的UDP数据报，然后将TTL字段每次加1，以确定路径中的每个路由器。每个路由器在丢弃UDP数据报时都返回一个ICMP超时报文2，而最终目的主机则产生一个ICMP端口不可达的报文



- 还有一种以前没有碰到过的情况是在TTL字段为8的情况下，对于第一个RT T，打印一个星号。这表明，发生超时，在5秒内未收到本次探查的应答信号

**Comment by 0XFF-96** [comment]
### IP 选路

### 内核是如何维护路由表的?

1. 搜索匹配的主机地址
2. 搜索匹配的网络地址；
3. 搜索默认表项（默认表项一般在路由表中被指定为一个网络表项，其网络号为0）

### flags 

- U 该路由可以使用。
- G 该路由是到一个网关（路由器）。如果没有设置该标志，说明目的地是直接相连的。
- H 该路由是到一个主机，也就是说，目的地址是一个完整的主机地址。如果没有设置该标志，说明该路由是到一个网络，而目的地址是一个网络地址：一个网络号，或者网络号与子网号的组合。
- D 该路由是由重定向报文创建的
- M 该路由已被重定向报文修改

### 路由表的初始化


### Op

一、路由表
```
查看所有路由表
netstat -rn
```

二、默认网关
```
route -n get default
route -n get www.yahoo.com
```


### 为什么常见路由器的网关默认 IP 都是 192.168.1.1 ?
- https://www.zhihu.com/question/20185640

### 为什么局域网的 IP 普遍以 192.168 开头？
- https://www.zhihu.com/question/19813460


> 集中讨论了单个系统是如何利用路由表的。在下一章，我们将讨论路由器之间是如何交换路由信息的

**Comment by 0XFF-96** [comment]
### 动态路由策略

- 路由之间的通讯协议， 选路信息协议(Routing Infromation Protocol)


### 动态路由

> 当相邻路由器之间进行通信，以告知对方每个路由器当前所连接的网络，这时就出现了动态选路

- 路由是由路由守护程序动态地增加或删除，而不是来自于自引导程序文件中的route命令



### 内部网关协议和外部网关协议
- 每个自治系统可以选择该自治系统中各个路由器之间的选路协议。这种协议我们称之为内部网关协议IGP（Interior Gateway Protocol）
- IGP是开放最短路径优先OSPF（Open Shortest Path First）
- 边界网关协议BGP（Border Gateway Protocol）。BGP意在取代EGP

### RIP 的 routed 程序

- 初始化
- 接收到请求
- 接收到响应
- 定期选路更新
- 触发更新

### RIP 与 OSPF（开放最短路径优先） 

- 他们两个路由表的建立方式不一样

- RIP 
```
距离向量的意思是，RIP发送的报文包含一个距离向量（跳数）。每个路由器都根据它所接收到邻站的这些距离向量来更新自己的路由表
```

- OSPF 
```
 在一个链路状态协议中，路由器并不与其邻站交换距离信息。它采用的是每个路由器主动地测试与其邻站相连链路的状态，将这些信息发送给它的其他邻站，而邻站将这些信息在自治系统中传播出去。每个路由器接收这些链路状态信息，并建立起完整的路由表
```



### 什么是 AS 自治系统？

BGP系统与其他BGP系统之间交换网络可到达信息。这些信息包括数据到达这些网络所必须经过的自治系统AS中的所有路径。这些信息足以构造一幅自治系统连接图



> 每条路由都有与之相关的定时器。 在一定时间内，被被 invalidate 掉。

### 总结

> 路由表项的内容很简单，包括：5bit标志、目的IP地址（主机、网络或默认）、下一站路由器的IP地址（间接路由）或者本地接口的IP地址（直接路由）及指向本地接口的指针

**Comment by 0XFF-96** [comment]
### TCP/UDP  伪首部的作用。

![image](https://user-images.githubusercontent.com/19239600/89014721-86268980-d348-11ea-9d06-bcd6774ef36e.png)

- 不要完全相信数据链路（如以太网，令牌环等）的CRC检验。应该始终打开端到端的检验和功能

### 用 Traceroute 确定 路径 MTU  

> 改traceroute程序（第8章），用它来确定路径MTU。要做的是发送分组，并设置“不分片”标志比特。发送的第一个分组的长度正好与出口MTU相等，每次收到ICMP“不能分片”差错时（在上一节讨论的）就减小分组的长度

- ICMP不可达差错，它是新的路径MTU发现功能中的一部分（2.9节）。用Tr aceroute和UDP来观察路径MTU发现过程。还查看了UDP和ARP之间的接口，大多数的ARP实现在等待ARP应答时只保留最近传送给目的端的数据报

**Comment by 0XFF-96** [comment]
### 广播与多播

### 广播的分类
- 受限的广播
- 指向网络的广播
- 指向子网的广播
- 指向所有子网的广播


### 多播

IP 多播提供两类服务；
- 1、向多个目的地址传输数据。 
- 2、客户对服务器的请求。

**Comment by 0XFF-96** [comment]
### IGMP 
略
![image](https://user-images.githubusercontent.com/19239600/89018437-78740280-d34e-11ea-821f-f41e0e913253.png)
